### ISSUE TITLE
Sweep: Refactor the lowercase enums to uppercase in the source code but exclude the enums defined in the examples directory

### ISSUE THREAD

**Issue by blooop** [blooop/bencher#100]

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by kevinlu1248** [comment]
Hey @blooop, how does this look? Feel free to re-trigger this as well by typing "sweep: ..."

**Comment by blooop** [comment]
I replied to a couple of the pr changes, but sweep seemed to get more confused the more I replied.  I think it would have a better chance if I started from scratch.   The changes it suggests here are not correct as it has mistaken classes for enums.  There is 1 set of enums in the plotting code which needs to be changed and all the other changes are not required (see my responses in the pr for more detail)

**Comment by kevinlu1248** [comment]
Sweep: The changes it suggests here are not correct as it has mistaken classes for enums. There is 1 set of enums in the plotting code which needs to be changed and all the other changes are not required (see my responses in the pr for more detail)

**Comment by kevinlu1248** [comment]
@blooop commenting on the issue creates a new PR. Also we're improving on the execution stage to avoid making unnecessary changes.

**Comment by blooop** [comment]
I have opened a new issue with clearer instructions so am closing this issue. So far sweep is doing a much better job with the improved instructions.
