### ISSUE TITLE
Sweep: Refactor PlotTypes enum to follow python enum conventions

### ISSUE THREAD

**Issue by blooop** [blooop/bencher#106]
### Details

The PlotTypes enum does not follow the python convention for enums where the values of the enum should have upper case names. 

Please refactor the enum values to uppercase and update all references to the new values.

E.g. PlotType.swarmplot should be refactored to PlotType.SWARMPLOT

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by blooop** [comment]
its failing to update the references.  It assumes that the errors are more complicated than pylint, but doesn't read the pylint output to check what the linting errors are.

**Comment by kevinlu1248** [comment]
Hey @blooop I have another heuristic for log extraction in mind that I'll implement soon. I'll lyk when it's out.

**Comment by kevinlu1248** [comment]
Actually took a deeper look, looks like the logs are correct but how it handles it is wrong, is that correct?
